version: 2

aliases: [
  &dependency-paths [
    "node_modules",
    "checksum.txt",
  ],
  &output-paths [
    "build",
    "checksum.txt",
  ],
]

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.17

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run checksum
      - save_cache:
          paths: *dependency-paths
          key: v1-dependencies-{{ checksum "checksum.txt" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "checksum.txt" }}
      - run: npm run build
      - save_cache:
          paths: *output-paths
          key: v1-dist-{{ checksum "checksum.txt" }}

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dist-{{ checksum "checksum.txt" }}
            - v1-dependencies-{{ checksum "checksum.txt" }}
      - run: git config --global user.name "lenconda"
      - run: git config --global user.email i@lenconda.top
      - run: mkdir -p ~/.ssh
      - run: touch ~/.ssh/known_hosts
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install:
          filters:
            branches:
              ignore: /^gh\-pages$/
      - build:
          requires:
            - install
          filters:
            tags:
              ignore: /^publish@(\d+)/
      - deploy:
          requires:
            - install
          filters:
            tags:
              only:
                - /^publish@(\d+)/
            branches:
              ignore: /.*/
